FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /app

COPY . ./
RUN dotnet publish -c Release -o out TrafficDisplayModule.sln

FROM microsoft/dotnet:2.1-runtime-nanoserver-1809
WORKDIR /app
COPY --from=build-env /app/TrafficDisplaySimulatorModule/out/ ./
ENTRYPOINT ["dotnet", "TrafficDisplaySimulatorModule.dll"]